### ISSUE TITLE
Additional core permissions

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#615]
We have a multi-site where we'd like to be able to enforce, for `site3` users:
* No access or any kind to any `site1` & `site2` assets, entries, content in the CP.
* Only access to be able to EDIT EXISTING `site1` pages and content in the CP.
* No ability to add new content to `site``, or upload any new assets to `site1, only be able to associate existing assets in `site1`.

Step one, I think, of this would be permissions by site.

Step 2 would be either be more comprehensive built in permissions or the ability to better overwrite existing permission and create custom gates/policies that would handle this, along with some example in the docs on how to achieve.

Thanks!

**Comment by jesseleite** [comment]
Re: step 2 there, I had thought it might be possible to extend or override our policies, maybe something like this:

```php
Statamic::booted(function () {
    Gate::policy(\Statamic\Contracts\Entries\Entry::class, CustomEntryPolicy::class);
});
```

Maybe it's already possible to extend our policies, but I had no luck in my quick test.

**Comment by adnankussair** [comment]
@jackmcdade

### The Ask
Ability for assigning multisite permissions to isolate user access to a single specific multisite and its relevant assets/content

### Use Case
Our specific use case involves larger organizations which have subsidiary sites which they would like on one unified installation. Hence users with admin at the org would have access to all sites under one login, but individual brand managers for each subsidiary would only have access to their relevant site. The biggest advantage here that we pitched was a single unified code base that will reduce maintenance costs while promoting iterative improvements which would cascade to all web properties under that unified codebase.

### Tasks
- [ ] Add permissions that allow restricting a user to ONLY access ALL content in specific site
- [ ] Add permissions that allow restricting a user to only access/edit/etc a specific collection in a specific site
- [ ] Add permissions that allow restricting a user to only access assets connected to a specific site

**Comment by jasonvarga** [comment]
Thanks for the ping. Closing this in favor of https://github.com/statamic/cms/issues/2667
